### ISSUE TITLE
Website Enhancement: Add Section for Speaker Affiliated Companies

### ISSUE THREAD

**Issue by SeifElbayomi** [devopsdays/devopsdays-web#14352]
**Proposal**: Add a new section titled "Learn from and network with speakers from the following companies" to the DevOpsDays event website.

**Placement**: Below the sponsors section to ensure sponsors remain prominent.

**Content**: Display logos of companies our speakers are affiliated with, clearly differentiated from sponsor logos.

**Example main.yml Addition:**

```
speaker_companies:
  - id: google
  - id: harness
  - id: ibm
  - id: aiven
  - id: redhat
  - id: nokia  
```

**Placement Screenshot:**
![Screenshot 2024-07-15 141552](https://github.com/user-attachments/assets/5312c26a-a1cb-4daa-afa8-cea45f4d501f)

**This enhancement will attract more attendees by showcasing reputable companies associated with our speakers while maintaining the prominence of our sponsors.**
