### ISSUE TITLE
Add ability to override sponsor section titles

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#14456]
Connected to #14440

Today, when you set a sponsor level, that word is put in front of "sponsor(s)" and all the other places that sponsorship is referred to (i.e., if  the level if "Silver", it will be referred to as "Silver Sponsors"). A case has come up for sponsorship levels which the organizers would prefer to not include the word "sponsor".

I would suggest that this could be implemented with an optional override on the title for a sponsor level (similar to URL overrides on the navigation):

```yaml
nav_elements: # List of pages you want to show up in the navigation of your page.
  - name: propose
    url: https://talks.devopsdays.org/devopsdays-chicago-2025/cfp
```

so something like this:

```yaml
sponsor_levels:
  - id: platinum
    label: Platinum
    max: 2
  - id: gold
    label: Gold
  - id: academic
    display: Academic Supporters
```

It would be confusing slightly, because it's like "Label" is what is used if you want "...Sponsor(s)" appended, and "display" is the override. Maybe it would be called `display_override` to be clear?
