### ISSUE TITLE
Add make_new_program.sh to generate program page and YAML

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1665]
This will create the proper YAML for dynamic program pages, as well as create the proper `program.md` or whatever.

**Comment by mattstratton** [comment]
The YAML should look like this:

```
program:
  - title: "Registration, Breakfast, and Sponsor Booths Open"
    type: custom
    date: 2016-01-01
    start_time: "08:00"
    end_time: "09:00"
  - title: "Opening Welcome"
    type: custom
    date: 2016-01-01
    start_time: "09:15"
    end_time: "09:00"
  - title: "rainbow-dash"
    type: talk
    date: 2016-01-01
    start_time: "09:15"
    end_time: "09:45"
  - title: "Sponsors"
    type: custom
    date: 2016-01-01
    start_time: "09:45"
    end_time: "09:55"
  - title: "apple-jack"
    type: talk
    date: 2016-01-01
    start_time: "09:55"
    end_time: "10:25"
  - title: "Break"
    type: custom
    date: 2016-01-01
    start_time: "10:25"
    end_time: "10:40"
  - title: "fluttershy"
    type: talk
    date: 2016-01-01
    start_time: "10:40"
    end_time: "11:10"
  - title: "Sponsors"
    type: custom
    date: 2016-01-01
    start_time: "11:10"
    end_time: "11:20"
  - title: "twilight-sparkle"
    type: talk
    date: 2016-01-01
    start_time: "11:20"
    end_time: "11:50"
  - title: "Lunch (catered)"
    type: custom
    date: 2016-01-01
    start_time: "11:50"
    end_time: "13:00"
```
