### ISSUE TITLE
Ignites can't be broken into two blocks on the same day

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#6543]
I noticed when fixing https://github.com/devopsdays/devopsdays-web/pull/5338 that we didn't seem to be able to break the Ignite talks for one day up into two different blocks. We probably want to support this.

**Comment by mattstratton** [comment]
I am looking at this again...I think that it would work pretty okay if it was something like this:

```yaml
program:
  - title: "Ignites Round 1"
    type: ignite
    ignite-id: 1
    date: 2019-08-27
    start_time: "13:00"
    end_time: "13:30"
  - title: "Ignites Round 2"
    type: ignite
    ignite-id: 2
    date: 2019-08-27
    start_time: "16:00"
    end_time: "16:30"

ignites:
  - title: "veronica-hanus"
    date: 2019-08-27
    ignite-id: 1
  - title: "jay-gordon"
    date: 2019-08-27
    ignite-id: 1
  - title: "adam-shake"
    date: 2019-08-27
    ignite-id: 1
  - title: "j-paul-reed"
    date: 2019-08-27
    ignite-id: 2
  - title: "michael-stahnke"
    date: 2019-08-27
    ignite-id: 2
  - title: "jason-yee"
    date: 2019-08-27
    ignite-id: 2
```

so when it is drawing ignites, there's a slightly different query; if the ignite program element has `ignite-id` set, then it queries for both the date AND the `ignite-id`; if not, it queries for ignites that do NOT have it set (that will handle the backwards compat).
