### ISSUE TITLE
Provide RSS Feed for Event Details

### ISSUE THREAD

**Issue by thedavecarroll** [devopsdays/devopsdays-web#7939]
Using data files as source, provide two RSS feeds, one for all events and another just for upcoming events, that contain all details for events.

Null entries are acceptable.

```yml
name:
year:
city:
event_twitter:
description:

startdate:
enddate:

cfp_date_start:
cfp_date_end:
cfp_date_announce:
cfp_open:
cfp_link:

registration_date_start:
registration_date_end:
registration_closed:
registration_link:

coordinates:
location:
location_address:

team_members:
  - name:
    role:
    email:
    twitter:
    github:
    linkedin:
    employer:
    website:
organizer_email:
proposal_email:
sponsors: 
  - id:
    level:
    url:
sponsors_accepted:
```

After September, I may be able to assist with this.

Thanks!
