### ISSUE TITLE
Add image compression to pull requests

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#8273]
Suggested by @mrbusche, we should add the [image-actions](https://github.com/marketplace/actions/image-actions) GitHub action to automatically perform compression on images in PR's.

**Comment by mattstratton** [comment]
This workflow seems to take a really long time to run (it's at >13m right now and it's not done yet in my first test).

It seems like with GitHub Actions we can set an action to run only on specific branches; maybe what we could do is create a naming standard and manually push PR's from that branch every now and again to optimize all the images, something like:

```
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'performance/*'   # Push events to branches matching refs/heads/performance/*
```

So for example, if I want to run an image optimization, I would run `git checkout -b performance/matt-perf` and then push that branch up and kick a PR. That would, in theory, only run the GH image optimization on that branch.

**Comment by mattstratton** [comment]
Oh! You can run actions on a schedule:

https://help.github.com/en/articles/workflow-syntax-for-github-actions#onschedule

```
You can schedule a workflow to run at specific UTC times using POSIX cron syntax. Scheduled workflows run on the latest commit on the default or base branch.
```

If we wanted it to run every day against `master` at 2am, it would look like this:

```
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * *'
```

I think the schedule is the best way to do it. Thoughts, @adrianmoisey and @bridgetkromhout 	?
